(define (problem hacer-pollo)
   (:domain hacer-pollito)
   (:objects p5 p4 p3 p2 p1 m2 m1 r3 r2 r1 s2 s1 )

   (:init (pollo p5)
          (pollo p4)
          (pollo p3)
          (pollo p2)
          (pollo p1)
          (mantequilla m2)
          
          (mantequilla m1)
          (recipiente r3)
          (recipiente r2)
          (recipiente r1)
          (sarten s2)
          (sarten s1)
          (estufa-on))

    (:goal (and (pollo-cocido)
                (polloEnRecipiente)
                (estufa-on)
    ))
)